stages:
  - lint
  - build
  - deploy

variables:
  DOCKER_IMAGE: $DOCKERHUB_USERNAME/social_web_teneta  # Название образа
  DOCKER_TAG: latest  # Тег образа (можно указать, например, $CI_COMMIT_REF_NAME для ветки)
  IMAGE_FILE: docker-image.tar

lint:
  stage: lint
  image: python:3.12
  before_script:
    - python -m venv venv
    - source venv/bin/activate
    - pip install -r requirements.txt
  script:
    - pylint $(git ls-files '*.py') --output-format=colorized > pylint_report.txt || true
  artifacts:
    paths:
      - pylint-report.txt
    when: always
  allow_failure: true

before_script:
  - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

build:
  stage: build
  image: docker:24.0.2  # Образ с Docker для CI
  services:
    - docker:24.0.2-dind  # Запускает Docker-in-Docker для сборки
  script:
    - docker build -t $DOCKER_IMAGE:$DOCKER_TAG .  # Собираем Docker-образ
    - docker save -o $IMAGE_FILE $DOCKER_IMAGE:$DOCKER_TAG
  artifacts:
    paths:
      - $IMAGE_FILE

deploy:
  stage: deploy
  image: docker:24.0.2
  services:
    - docker:24.0.2-dind
  script:
    - docker load -i $IMAGE_FILE
    - docker push $DOCKER_IMAGE:$DOCKER_TAG  # Пушим образ в DockerHub
  dependencies:
    - build
