stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE: $DOCKERHUB_USERNAME/social-web-teneta  # Название образа
  DOCKER_TAG: latest  # Тег образа (можно указать, например, $CI_COMMIT_REF_NAME для ветки)

before_script:
  - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

build:
  stage: build
  image: docker:24.0.2  # Образ с Docker для CI
  services:
    - docker:24.0.2-dind  # Запускает Docker-in-Docker для сборки
  script:
    - docker build -t $DOCKER_IMAGE:$DOCKER_TAG .  # Собираем Docker-образ

deploy:
  stage: deploy
  image: docker:24.0.2
  services:
    - docker:24.0.2-dind
  script:
    - docker push $DOCKER_IMAGE:$DOCKER_TAG  # Пушим образ в DockerHub
