image: docker:24.0.2

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:24.0.2-dind

stages:
  - build
  - test
  - security
  - deploy

build:
  stage: build
  script:
    - docker build -t $CI_REGISTRY_IMAGE:latest .
    - docker tag $CI_REGISTRY_IMAGE:latest docker.io/$DOCKERHUB_USERNAME/social_web_teneta:latest

test:
  stage: test
  services:
    - name: postgres:latest
      alias: db
      variables:
        POSTGRES_DB: POSTGRES_DB
        POSTGRES_HOST: $POSTGRES_HOST
        POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    - name: redis:alpine
      alias: redis
  image: python:3.12
  script:
    - pip install -r requirements.txt
    - python manage.py makemigrations
    - python manage.py migrate

lint:
  stage: test
  image: python:3.12
  script:
    - pip install black
    - black --check .
  allow_failure: true

sast:
  stage: security
  image: docker:24.0.2
  script:
    - apk add --no-cache python3 py3-pip gcc python3-dev musl-dev linux-headers
    - python3 -m venv /venv
    - source /venv/bin/activate
    - pip install bandit
    - bandit -r .
  allow_failure: true

trufflehog:
  stage: security
  image: trufflesecurity/trufflehog:latest
  script:
    - trufflehog filesystem .
  allow_failure: true

deploy:
  stage: deploy
  script:
    - echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
    - docker push $DOCKERHUB_USERNAME/social_web_teneta:latest
  when: on_success

cache:
  paths:
    - .pip_cache/
