# Generated by Django 5.0.2 on 2024-02-29 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0002_rename_user_post_author_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
