# Generated by Django 5.0.6 on 2024-12-19 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profile_pic', models.ImageField(blank=True, default='profile/default.png', upload_to='profile')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('subscription', models.ManyToManyField(blank=True, to='profile.profile')),
            ],
        ),
    ]
