# Generated by Django 5.0.2 on 2024-04-10 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0006_profile_following_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='following',
        ),
    ]
