# Generated by Django 5.0.2 on 2024-04-10 08:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0008_profile_followers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='user',
            new_name='subscriber',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='followers',
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('subscriber', 'subscribed_to')},
        ),
    ]
