# Generated by Django 5.0.6 on 2024-05-14 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0011_remove_profile_followers_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', to='Profile.profile'),
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
